# The bot token
token: "DISCORD_BOT_TOKEN_HERE"

# Google AI API Key
googleAiApiKey: "YOUR_GOOGLE_AI_API_KEY_HERE"

# AI System Prompt
aiSystemPrompt: "You are a helpful Discord bot assistant created by braidenhxyz. Current date and time: {datetime} UTC. You should be friendly, concise, and helpful. If asked about sensitive topics, respond appropriately for a Discord server environment. Always be respectful and follow Discord's community guidelines. You are running in a Discord server and should format your responses appropriately for Discord markdown when needed."

# Discord IDs of people permitted to use the bot
permittedIds:
  - "YOUR_ID_HERE"

#Feel free to change your colors of the embeds
embeds:
  colors:
    normal: "#2563eb"
    error: "#dc2626"
    success: "#16a34a"
