# The bot token
token: "DISCORD_BOT_TOKEN_HERE"

# Discord IDs of people permitted to use the bot
permittedIds:
  - "YOUR_ID_HERE"

#Feel free to change your colors of the embeds
embeds:
  colors:
    normal: "#2563eb"
    error: "#dc2626"
    success: "#16a34a"
